---

driver:
     name: azurerm

driver_config:
     subscription_id: 'a06a99f4-9123-4ef6-94d8-e669b8f6f61e'
     location: 'West Europe'
     machine_size: 'Standard_D1'
     username: msghaleb
     password: Start1!Start1!

transport:
  #ssh_key: ~/.ssh/id_kitchen-azurermtransport
     name: winrm
     winrm_transport: negotiate

provisioner:
    name                  : ansible_push
    #verbose               : "vvvv"
    ansible_config        : "test/ansible.cfg"
    idempotency_test      : 'True'
    diff                  : 'True'
    chef_bootstrap_url    : nil
    ansible_connection    : "winrm"

platforms:
  - name: windows-2012
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:4.0.20160430
      vm_name: win-2012-r2-vm

suites:
  - name                  : default
    provisioner           :
        playbook          : "test/integration/default/default.yml"
